from mnist_image_classification.service.model_manager import ModelManager
from mnist_image_classification.service.service import app
from mnist_image_classification.service.service import load_models